/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mfbtrans;

import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Ikpe
 */
public class Cashposition extends javax.swing.JFrame implements Printable{
@Override
      public int print(Graphics g, PageFormat pf, int page) throws PrinterException { 
        if (page>0){
            return NO_SUCH_PAGE;
        }  
         Graphics2D g2d=(Graphics2D)g;
        int x=(int)pf.getImageableX();
        int y=(int)pf.getImageableY();
        g2d.scale(0.8, 1);
        g2d.translate(x, y);
     jPanelcp.paintAll(g);//does the actual printing
         return PAGE_EXISTS;
    }
    /**
     * Creates new form Cashposition
     */
    public Cashposition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelcp = new javax.swing.JPanel();
        jLabelMFI = new javax.swing.JLabel();
        jLabeltitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecp = new javax.swing.JTable();
        jLabeltitle1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CASH POSITION");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelcp.setBackground(new java.awt.Color(255, 255, 255));

        jLabelMFI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMFI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMFI.setText("MFI NAME");

        jLabeltitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltitle.setText("MFI NAME");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTablecp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Description", "Balance", "Breakdown", "Remark"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablecp.setShowHorizontalLines(isEnabled());
        jTablecp.setShowVerticalLines(isEnabled());
        jScrollPane1.setViewportView(jTablecp);
        if (jTablecp.getColumnModel().getColumnCount() > 0) {
            jTablecp.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        jLabeltitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeltitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltitle1.setText("MIS SIGN:_____________                                          BM SIGN:___________________");

        javax.swing.GroupLayout jPanelcpLayout = new javax.swing.GroupLayout(jPanelcp);
        jPanelcp.setLayout(jPanelcpLayout);
        jPanelcpLayout.setHorizontalGroup(
            jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcpLayout.createSequentialGroup()
                .addGroup(jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelcpLayout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelcpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMFI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabeltitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelcpLayout.setVerticalGroup(
            jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcpLayout.createSequentialGroup()
                .addComponent(jLabelMFI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabeltitle1))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelcp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      jLabelMFI.setText(companyname);
      jLabeltitle.setText("Cash Position As At "+ses_date.substring(0,10));
      String qCasha="select sum(amount) Credit from Transactn " +
"where  CreditGL like'11102-%'";
      String qCashb="select sum(amount)debit from Transactn " +
"where debitGL like'11102-%'";
      String qBanka="select isnull(sum(isnull(amount,0)),0 ) Credit from Transactn " +
"where  CreditGL like'112%'"; 
      String qBankb="select isnull(sum(isnull(amount,0)),0 ) debit from Transactn " +
"where debitGL like'112%'"; 
      String qLoan="select SUM(outstandingbal) LoanBal from loans";
      String qDeposit="select SUM(Runningbal) DepositBal from deposit";
      String qborrower="select COUNT(distinct custno) borrower from loans where Status='Active'";
      String qSaver="select COUNT(distinct custno) saver from deposit where Status='Active'";
             String qOverdue=  "select sum(RepayWithInt)-SUM(servicedInt+ServicedPrin)  \n" +
" as OVAPLusInt,sum(PrinRepay-ServicedPrin) as OVAprinOnly from Loanschedule ls inner join Loans l on l.LoanID=ls.LoanID inner join \n" +
" (select LoanID,min(date) as lastPayDate from Loanschedule " +
" where Status ='not serviced' or Status ='Partial' group by custno,LoanID)  d  on d.LoanID=ls.LoanID \n" +
" where l.status= 'Active' and date<='"+ses_date.substring(0,10)+"' " +
" having sum(PrinRepay-ServicedPrin)>1";
    BigDecimal CashDebit=BigDecimal.ZERO,CashCredit=BigDecimal.ZERO,BankDebit=BigDecimal.ZERO,BankCredit=BigDecimal.ZERO;   
          
          
      try{
          this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
          Statement stmt=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY );
          //Running for Cash Balance
           ResultSet rs =stmt.executeQuery(qCasha);
         if(rs.next()){
           CashCredit=rs.getBigDecimal("Credit");
         }
         rs =stmt.executeQuery(qCashb);
         if(rs.next()){
           CashDebit=rs.getBigDecimal("Debit");
         }
         jTablecp.getModel().setValueAt("Cash Balance", 0, 0);
         jTablecp.getModel().setValueAt(thseparate((CashDebit.subtract(CashCredit)).setScale(2,RoundingMode.HALF_UP)) , 0, 1);
         ///Running for Bank Balances
             rs =stmt.executeQuery(qBanka);
         if(rs.next()){
           BankCredit=rs.getBigDecimal("Credit");
         }
         rs =stmt.executeQuery(qBankb);
         if(rs.next()){
           BankDebit=rs.getBigDecimal("Debit");
         }
         jTablecp.getModel().setValueAt("Bank Balance", 4, 0);
         jTablecp.getModel().setValueAt(thseparate((BankDebit.subtract(BankCredit)).setScale(2,RoundingMode.HALF_UP).negate()) ,4, 1);
         //Running for loan Balance
         rs =stmt.executeQuery(qLoan);
         if(rs.next()){
          
            jTablecp.getModel().setValueAt(thseparate(rs.getBigDecimal("LoanBal").setScale(2,RoundingMode.HALF_UP).negate()) ,8, 1);

         }
         jTablecp.getModel().setValueAt("Total Loan Balance", 8, 0);
         //Running for Deposit Balance
         rs =stmt.executeQuery(qDeposit);
         if(rs.next()){
          
            jTablecp.getModel().setValueAt(thseparate(rs.getBigDecimal("DepositBal").setScale(2,RoundingMode.HALF_UP)) ,12, 1);

         }
         jTablecp.getModel().setValueAt("Total Deposit Balance", 12, 0);
         //Running for Borrowers
         rs =stmt.executeQuery(qborrower);
         if(rs.next()){
          
            jTablecp.getModel().setValueAt(thseparate(rs.getBigDecimal("borrower")).replaceFirst(".00", "")  ,16, 1);

         }
         jTablecp.getModel().setValueAt("Total Borrowers", 16, 0);
         //Running for Savers
         rs =stmt.executeQuery(qSaver);
         if(rs.next()){
          
            jTablecp.getModel().setValueAt(thseparate(rs.getBigDecimal("saver")).replaceFirst(".00", "")  ,20, 1);

         }
         jTablecp.getModel().setValueAt("Total Savers", 20, 0);
         
         //Running for overdue
         
         rs =stmt.executeQuery(qOverdue);
         if(rs.next()){
          
            jTablecp.getModel().setValueAt(thseparate(rs.getBigDecimal("Ovaplusint").setScale(0,RoundingMode.HALF_UP)) ,25, 1);
            jTablecp.getModel().setValueAt(thseparate(rs.getBigDecimal("OvaPrinonly").setScale(0,RoundingMode.HALF_UP) ),25, 2);

         }
         jTablecp.getModel().setValueAt("Overdue (Prin +Int) and Prin only ", 25, 0);
         //jTablecp.getModel().setValueAt("MIS SIGN:___________ ", 28, 0);
         //jTablecp.getModel().setValueAt("BM SIGN:", 28, 1);
           jTablecp.getModel().setValueAt("________________", 28, 2);
         //
         
      }catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
      this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
PrinterJob job = PrinterJob.getPrinterJob();
        PageFormat format=job.defaultPage();
        format.setOrientation(PageFormat.PORTRAIT);
        job.setPrintable(this,format);
            boolean ok =job.printDialog();
            
            if(ok){
        try {
            
            job.print();// TODO add your handling code here:
        } catch (PrinterException ex) {
         JOptionPane.showMessageDialog(this, ex.getMessage());
        }
            }// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashposition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashposition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelMFI;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JLabel jLabeltitle1;
    private javax.swing.JPanel jPanelcp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablecp;
    // End of variables declaration//GEN-END:variables
Connection conn;
String companyname;
String compshortname;
String ses_date;
 public String thseparate(BigDecimal amount){
 DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.ENGLISH);
DecimalFormatSymbols symbols = formatter.getDecimalFormatSymbols();

symbols.setGroupingSeparator(',');
formatter.setDecimalFormatSymbols(symbols);
formatter.setMinimumFractionDigits(2);
return formatter.format((amount.setScale(2, RoundingMode.HALF_UP)));    

 }

}
