/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mfbtrans;

import com.sun.glass.events.KeyEvent;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.FieldPosition;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.image4j.codec.bmp.BMPDecoder;

/**
 *
 * @author Emmanuel Ikpe
 */
public class Clients extends javax.swing.JFrame {

    /**
     * Creates new form Clients
     */
    public Clients() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldacc = new javax.swing.JTextField();
        jTextFieldnuban = new javax.swing.JTextField();
        jTextFieldIDcard = new javax.swing.JTextField();
        jTextFieldbvn = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldregdate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldaddress = new javax.swing.JTextField();
        jTextFieldRefno = new javax.swing.JTextField();
        jTextFieldphone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableacc = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablehist = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldBalCU = new javax.swing.JTextField();
        jTextFieldBalU = new javax.swing.JTextField();
        jTextFieldBalC = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldgroup = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldBalWithInt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelpix = new javax.swing.JLabel();
        jLabelsign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Browse Clients");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane4.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane4.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane4ComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Branch");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("A/C NO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Bank Verification No");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NUBAN CODE");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OGOJA" }));
        jComboBox1.setToolTipText("");
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextFieldname.setEditable(false);
        jTextFieldname.setBackground(new java.awt.Color(204, 204, 190));
        jTextFieldname.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldacc.setEditable(false);
        jTextFieldacc.setBackground(new java.awt.Color(204, 204, 190));

        jTextFieldnuban.setEditable(false);
        jTextFieldnuban.setBackground(new java.awt.Color(204, 204, 190));

        jTextFieldIDcard.setEditable(false);
        jTextFieldIDcard.setBackground(new java.awt.Color(204, 204, 190));

        jTextFieldbvn.setEditable(false);
        jTextFieldbvn.setBackground(new java.awt.Color(204, 204, 190));

        jPanel1.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.setToolTipText("");

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jRadioButton1.setText("Name");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jRadioButton2.setText("A/C NO");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jRadioButton5.setText("Ref No");
        jRadioButton5.setOpaque(false);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton6.setText("ID Card");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jRadioButton3.setText("NUBAN Code");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jRadioButton4.setText("Bank Verification Number");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jRadioButton1)
                .addGap(0, 0, 0)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addGap(0, 0, 0)
                .addComponent(jRadioButton3)
                .addGap(0, 0, 0)
                .addComponent(jRadioButton4))
        );

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSeparator1.setOpaque(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfbtrans/searchicon.PNG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Capture And Verify FingerPrint");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel6.setOpaque(true);

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel7.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Registration Date");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Group Code/No");

        jTextFieldregdate.setEditable(false);
        jTextFieldregdate.setBackground(new java.awt.Color(204, 204, 190));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Ref No:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("Phone No:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("ID Card:");

        jTextFieldaddress.setEditable(false);
        jTextFieldaddress.setBackground(new java.awt.Color(204, 204, 190));

        jTextFieldRefno.setEditable(false);
        jTextFieldRefno.setBackground(new java.awt.Color(204, 204, 190));

        jTextFieldphone.setEditable(false);
        jTextFieldphone.setBackground(new java.awt.Color(204, 204, 190));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTableacc.setBackground(new java.awt.Color(255, 153, 51));
        jTableacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title", "GL A/C NO", "A/C NO", "Loan Cycle", "A/C Balance", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableacc.setShowHorizontalLines(isEnabled());
        jTableacc.setShowVerticalLines(isEnabled());
        jTableacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableaccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableacc);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane2KeyPressed(evt);
            }
        });

        jTablehist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Trx Date", "Session Date", "Trx NO", "Text", "Amount", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablehist.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablehist.setCellSelectionEnabled(true);
        jTablehist.setFillsViewportHeight(true);
        jTablehist.setShowHorizontalLines(isEnabled());
        jTablehist.setShowVerticalLines(isEnabled());
        jTablehist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablehistKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTablehist);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("Total (Cleared + Uncleared)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("Cleared Balance");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("UnCleared Balance");

        jTextFieldBalCU.setBackground(new java.awt.Color(204, 204, 190));

        jTextFieldBalU.setBackground(new java.awt.Color(204, 204, 190));
        jTextFieldBalU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBalUActionPerformed(evt);
            }
        });

        jTextFieldBalC.setBackground(new java.awt.Color(204, 204, 190));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Go to Account ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("<html><u>Account Details</u></html>");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("<html><u>Transaction History</u></html>");

        jTextFieldgroup.setEditable(false);
        jTextFieldgroup.setBackground(new java.awt.Color(204, 204, 190));

        jButton3.setText("EXIT");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Prin + Int");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextFieldBalWithInt.setBackground(new java.awt.Color(204, 204, 190));
        jTextFieldBalWithInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBalWithIntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldacc, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(98, 98, 98)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(17, 17, 17)
                                                    .addComponent(jTextFieldnuban, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldbvn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(413, 413, 413)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldregdate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldRefno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldIDcard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBalWithInt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(180, 180, 180))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(96, 96, 96)
                                .addComponent(jTextFieldBalC, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldBalCU, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(83, 83, 83)
                                .addComponent(jTextFieldBalU, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, 0)
                                        .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldnuban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldbvn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRefno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldregdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldIDcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 29, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldBalCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(6, 6, 6))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBalU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldBalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jTextFieldBalWithInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );

        jTabbedPane4.addTab("                                             1. General                                     ", jPanel2);

        jLabelpix.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabelpix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpixMouseClicked(evt);
            }
        });

        jLabelsign.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabelpix, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelsign, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpix, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelsign, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("                              2. Photo and Signature                 ", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
         jRadioButton1.setSelected(false);  
      jRadioButton3.setSelected(false); 
      jRadioButton4.setSelected(false);  
      jRadioButton5.setSelected(false); 
      jRadioButton6.setSelected(false);
      searchType="Search on A/C NO";
      query="select custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where custno like'%";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      jRadioButton2.setSelected(false);  
      jRadioButton3.setSelected(false); 
      jRadioButton4.setSelected(false);  
      jRadioButton5.setSelected(false); 
      jRadioButton6.setSelected(false); 
      searchType="Search on A/C Name";
       query="select  custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where lastname+''+middlename+''+firstname like'%";

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextFieldBalUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBalUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBalUActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
 jRadioButton2.setSelected(false);  
      jRadioButton3.setSelected(false); 
      jRadioButton4.setSelected(false);  
      jRadioButton1.setSelected(false); 
      jRadioButton6.setSelected(false);
      searchType="Search on Ref NO";
      query="select  custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where refno like'%";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
 jRadioButton2.setSelected(false);  
      jRadioButton3.setSelected(false); 
      jRadioButton4.setSelected(false);  
      jRadioButton5.setSelected(false); 
      jRadioButton1.setSelected(false); 
      searchType="Search on ID Card";
      query="select custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where id_card like'%";
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
 jRadioButton2.setSelected(false);  
      jRadioButton1.setSelected(false); 
      jRadioButton4.setSelected(false);  
      jRadioButton5.setSelected(false); 
      jRadioButton6.setSelected(false);
      searchType="Search on NUBAN Code";
      query="select custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where nuban like'%";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
 jRadioButton2.setSelected(false);  
      jRadioButton3.setSelected(false); 
      jRadioButton1.setSelected(false);  
      jRadioButton5.setSelected(false); 
      jRadioButton6.setSelected(false);
      searchType="Search on BVN";
      query="select custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where BVN like'%";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jLabelpix.setIcon(null);
jLabelsign.setIcon(null);
search.jLabel1.setText(searchType);
search.query=query;
search.conn=conn;
search.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jRadioButton1.setSelected(true);  
Connection conn= glob.getConnect();
   try{
       Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
      
   
   String SQL="Select * from company";
    ResultSet current = stmt.executeQuery(SQL);
     current.next();
     ses_date=current.getString("ses_date");
companyname=current.getString("fullname");
compshortname=current.getString("shortname");

        current.close();
        conn.close();
        //JOptionPane.showMessageDialog(rootPane, glob.BranchCode);
        }
   catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}


    }//GEN-LAST:event_formWindowOpened

    private void jTabbedPane4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane4ComponentShown
                      // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane4ComponentShown

    private void jLabelpixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpixMouseClicked

this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try{
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                ResultSet current;

         current = stmt.executeQuery("select pix,sign from clients where custno="+search.cusno);
               current.next();
              // JOptionPane.showMessageDialog(rootPane,current.getString("sign") );
               if(current.getString("sign").startsWith("FFD")){
               
               byte[] fileBytes=current.getBytes("pix");
               ImageIcon pic=new ImageIcon(fileBytes);
     Image resizpic =pic.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
     ImageIcon resizIcon = new ImageIcon(resizpic);
   
    jLabelpix.setIcon(resizIcon);
         byte[] fileBytes2=current.getBytes("sign");
               ImageIcon sign=new ImageIcon(fileBytes2);
     Image resizpic2 =sign.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
     ImageIcon resizIcon2 = new ImageIcon(resizpic2);
           
            jLabelsign.setIcon(resizIcon2);   
               }
               else{
               String pixpath="\\\\Omfbserver\\e\\FinSolutions\\Photos\\"+current.getString("pix");
               String pixpath2="\\\\Omfbserver\\e\\FinSolutions\\Signature\\"+current.getString("sign");
               //checking for extension for signature
               if(pixpath2.contains(".bmp")||pixpath2.contains(".BMP")){
             
             BufferedImage image = BMPDecoder.read(new File(pixpath2));//signature
                    ImageIcon icon = new ImageIcon(image.getScaledInstance(100,100, Image.SCALE_SMOOTH));//signature
                  jLabelsign.setIcon(icon);//signature
                       //JOptionPane.showMessageDialog(this,current.getString("sphoto")+" and "+pixpath);
              }
              else{
               ImageIcon imageIconsign = new ImageIcon(new ImageIcon(pixpath2).getImage().getScaledInstance(120, 100, Image.SCALE_SMOOTH));//signature
               jLabelsign.setIcon(imageIconsign);//signature
                   }
              //check for file extension for photo
              if(pixpath.contains(".bmp")||pixpath.contains(".BMP")){
             
             BufferedImage image = BMPDecoder.read(new File(pixpath));//photo
                    ImageIcon icon = new ImageIcon(image.getScaledInstance(100,100, Image.SCALE_SMOOTH));//photo
                  jLabelpix.setIcon(icon);//photo
                       //JOptionPane.showMessageDialog(this,current.getString("sphoto")+" and "+pixpath);
              }
              else{
               ImageIcon imageIcon = new ImageIcon(new ImageIcon(pixpath).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));//photo
               jLabelpix.setIcon(imageIcon);//photo
                   }
               }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
         // TODO add your handling code here:
    }//GEN-LAST:event_jLabelpixMouseClicked

    private void jTableaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableaccMouseClicked
         //get openning Balances:
         if(!jTableacc.getModel().getValueAt(jTableacc.getSelectedRow(), 0).toString().isEmpty())
        {
         //JOptionPane.showMessageDialog(rootPane,jTableacc.getModel().getValueAt(jTableacc.getSelectedRow(), 0).toString());
         
        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         String today="",yr="",m="",d="";
        int i=0;
         try{
         StringBuffer stringBuffer = new StringBuffer();
         Date now = new Date();
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
         today=sdf.format(now, stringBuffer, new FieldPosition(0)).toString();
          yr=today.substring(6);m=today.substring(3,5);d=today.substring(0,2);
          
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage().replace("The result set has no current row", "No Transaction yet"));
         }
String glno=jTableacc.getModel().getValueAt(jTableacc.getSelectedRow(), 1).toString();
String accno=jTableacc.getModel().getValueAt(jTableacc.getSelectedRow(), 2).toString();
         String BBF=   "select runningbal Amt from transactn " +
" where custno='"+search.cusno+"' and accountid='"+accno+"'";                   


       String query2;     
// conn=glob.getConnect(); duplicate connection
  
                  try{
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
              
                  ResultSet current;         
                   current = stmt.executeQuery(BBF);
                 current.next();
                 
BigDecimal Bal= current.getBigDecimal("Amt").setScale(2, RoundingMode.HALF_UP);
//BigDecimal TrxAmt=BigDecimal.ZERO;
//set Cleared and Uncleared balances
jTextFieldBalCU.setText(thseparate(Bal)+"");
jTextFieldBalC.setText(thseparate(Bal)+"");
jTextFieldBalU.setText("0.00");

query2="select  distinct top 20  dateprocessing,dateEffective,transactionNbr,tranid num,custno,stmtRef,amount,runningbal from transactn" +
" where custno='"+search.cusno+"' and accountid='"+accno +"'"+
" order by  transactionNbr" ;
                        
                  current = stmt.executeQuery(query2);
                  //JOptionPane.showMessageDialog(rootPane, i);

         
               
                String DateFmt="",DateFmt2="";
                while(current.next()){
                    //format the Date 
                    DateFmt=  current.getString("dateprocessing").substring(0,10);
                  DateFmt2=  current.getString("dateEffective").substring(0,10);
                  DateFmt=DateFmt.substring(8)+"/"+DateFmt.substring(5,7)+"/"+DateFmt.substring(0,4);
                  DateFmt2=DateFmt2.substring(8)+"/"+DateFmt2.substring(5,7)+"/"+DateFmt2.substring(0,4);

                   jTablehist.getModel().setValueAt(  DateFmt2, i, 0);
                   jTablehist.getModel().setValueAt(  DateFmt, i, 1);
                   jTablehist.getModel().setValueAt(  current.getString("num"), i, 2);
                   jTablehist.getModel().setValueAt(  current.getString("stmtref"), i, 3);
                  // Bal=Bal.subtract(TrxAmt);
                    jTablehist.getModel().setValueAt(  thseparate(current.getBigDecimal("amount")), i, 4);
                  jTablehist.getModel().setValueAt(   thseparate(current.getBigDecimal("runningbal")), i, 5);
                //TrxAmt=current.getBigDecimal("amount");
            
               
               
               
              i=i+1;  
            }
               PrevAccHistCount=PrevAccHistCount-i;// to obtain and remove prev hist from appearing below.
                    if (searchtrue && PrevAccHistCount>0){
                        for(int k=i; k<= (i+PrevAccHistCount);k++){       
                            jTablehist.getModel().setValueAt(  "", k, 0);
                            jTablehist.getModel().setValueAt(  "", k, 1);
                            jTablehist.getModel().setValueAt(  "", k, 2);
                            jTablehist.getModel().setValueAt(  "", k, 3);

                            jTablehist.getModel().setValueAt(  "", k, 4);
                            jTablehist.getModel().setValueAt( "", k, 5);

                        }

                    }
                PrevAccHistCount=i;
                searchtrue=true;
                current.close();
              
                  }
            catch(SQLException e){ JOptionPane.showMessageDialog(this,e.getMessage().replace("The result set has no current row", "No Transaction yet"));
            }
                  this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
  jTablehist.requestFocusInWindow();
        }//end of overall if statement
    }//GEN-LAST:event_jTableaccMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            conn.close();        // TODO add your handling code here:
        } catch (SQLException ex) {
         //error was suppressed
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        if(!search.accno.equalsIgnoreCase("n")){
    //JOptionPane.showMessageDialog(rootPane, search.accno);

jTextFieldname.setText(search.acctitle.trim());  
jTextFieldacc.setText(search.accno.trim()); 
jTextFieldnuban.setText(search.nuban); 
jTextFieldbvn.setText(search.BVN); 
jTextFieldaddress.setText(search.addr); 
jTextFieldregdate.setText(search.regdate.substring(8,10)+"/"+search.regdate.substring(5,7)+"/"+search.regdate.substring(0,4)); 
jTextFieldgroup.setText(search.groupname); 
jTextFieldRefno.setText(search.ref);  
jTextFieldphone.setText(search.phone); 
jTextFieldIDcard.setText(search.idcard); 
//JOptionPane.showMessageDialog(this,conn);
conn=glob.getConnect(); //duplicate connection
//JOptionPane.showMessageDialog(rootPane, search.accnoonly);
String q="select custno,accountid,accountname,status,runningbal amt from Deposit  " +
" where custno='"+ search.cusno+"'"
        + "union all"
        + " select custno,loanid,accountname,status,OutstandingBal amt from loans"
        + " where custno='"+ search.cusno+"' order by  accountid ";
 //this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
 if(searchtrue){
 for(int k=0; k<accCount;k++){
     jTableacc.getModel().setValueAt(  "", k, 0);
                    jTableacc.getModel().setValueAt(  "", k, 1);
                   jTableacc.getModel().setValueAt(  "", k, 2);
                    jTableacc.getModel().setValueAt(  "", k, 3);
                   
                     jTableacc.getModel().setValueAt(  "", k, 4);
                 jTableacc.getModel().setValueAt( "", k, 5);
                  
            
    }
 }
String status;
try{
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                ResultSet current = stmt.executeQuery(q);
           
           
                int j=0;
                 while(current.next()){
                     jTableacc.getModel().setValueAt(current.getString("accountname"), j, 0);
                    jTableacc.getModel().setValueAt(current.getString("custno"), j, 1);
                    jTableacc.getModel().setValueAt(current.getString("accountID"), j, 2);
                   

                    jTableacc.getModel().setValueAt("0", j, 3);
                   status=current.getString("status");
                jTableacc.getModel().setValueAt(thseparate( current.getBigDecimal("amt")), j,4 );
                    jTableacc.getModel().setValueAt(status, j, 5);

                     j=j+1;
                 }
                  accCount=j;
                 int n=0;
                 
                /* while(j>=0){
                 String qq="select runningbal as amt from Deposit " +
" where custno='"+jTableacc.getModel().getValueAt(n, 1)+"' and accountid= '"+jTableacc.getModel().getValueAt(n, 2)+"'";
                      current = stmt.executeQuery(qq);
                      current.next();
                      jTableacc.getModel().setValueAt(thseparate( current.getBigDecimal("amt")), n,4 );
                       j=j-1; 
                       n=n+1;
                 }
                */
                   
              
                  
                 current.close();                     

                 
}
catch(Exception e){//JOptionPane.showMessageDialog(rootPane, e.getMessage());
} 

////fetch account history for first row


 //get openning Balances:
         if(!jTableacc.getModel().getValueAt(0, 0).toString().isEmpty())
        {
         //JOptionPane.showMessageDialog(rootPane,jTableacc.getModel().getValueAt(jTableacc.getSelectedRow(), 0).toString());
         
        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         String today="",yr="",m="",d="";
        int i=0;
         try{
         StringBuffer stringBuffer = new StringBuffer();
         Date now = new Date();
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
         today=sdf.format(now, stringBuffer, new FieldPosition(0)).toString();
          yr=today.substring(6);m=today.substring(3,5);d=today.substring(0,2);
          
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getCause());
         }
String glno=jTableacc.getModel().getValueAt(0, 1).toString();
String accno=jTableacc.getModel().getValueAt(0, 2).toString();
         String BBF=   "select runningbal Amt from transactn " +
" where custno='"+search.cusno+"' and accountid='"+accno+"'";                   


       String query2;     
 //conn=glob.getConnect(); duplicate connection
  
                  try{
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
              
                  ResultSet current;         
                   current = stmt.executeQuery(BBF);
                 current.next();
                 
BigDecimal Bal= current.getBigDecimal("Amt").setScale(2, RoundingMode.HALF_UP);
//BigDecimal TrxAmt=BigDecimal.ZERO;
//set Cleared and Uncleared balances
jTextFieldBalCU.setText(thseparate(Bal)+"");
jTextFieldBalC.setText(thseparate(Bal)+"");
jTextFieldBalU.setText("0.00");

query2="select  distinct top 20  dateprocessing,dateEffective,transactionNbr,tranid num,custno,stmtRef,amount,runningbal from transactn" +
" where custno='"+search.cusno+"' and accountid='"+accno +"'"+
" order by  transactionNbr  " ;
                        
                  current = stmt.executeQuery(query2);
                  //JOptionPane.showMessageDialog(rootPane, i);

         
               
                String DateFmt="",DateFmt2="";
                while(current.next()){
                    //format the Date 
                    DateFmt=  current.getString("dateprocessing").substring(0,10);
                  DateFmt2=  current.getString("dateEffective").substring(0,10);
                  DateFmt=DateFmt.substring(8)+"/"+DateFmt.substring(5,7)+"/"+DateFmt.substring(0,4);
                  DateFmt2=DateFmt2.substring(8)+"/"+DateFmt2.substring(5,7)+"/"+DateFmt2.substring(0,4);

                   jTablehist.getModel().setValueAt(  DateFmt2, i, 0);
                   jTablehist.getModel().setValueAt(  DateFmt, i, 1);
                   jTablehist.getModel().setValueAt(  current.getString("num"), i, 2);
                   jTablehist.getModel().setValueAt(  current.getString("stmtref"), i, 3);
                  // Bal=Bal.subtract(TrxAmt);
                    jTablehist.getModel().setValueAt(  thseparate(current.getBigDecimal("amount")), i, 4);
                  jTablehist.getModel().setValueAt(   thseparate(current.getBigDecimal("runningbal")), i, 5);
                //TrxAmt=current.getBigDecimal("amount");
            
               
               
               
              i=i+1;  
            }
                PrevAccHistCount=PrevAccHistCount-i;// to obtain and remove prev hist from appearing below.
                    if (searchtrue && PrevAccHistCount>0){
                        for(int k=i; k<= (i+PrevAccHistCount);k++){       
                            jTablehist.getModel().setValueAt(  "", k, 0);
                            jTablehist.getModel().setValueAt(  "", k, 1);
                            jTablehist.getModel().setValueAt(  "", k, 2);
                            jTablehist.getModel().setValueAt(  "", k, 3);

                            jTablehist.getModel().setValueAt(  "", k, 4);
                            jTablehist.getModel().setValueAt( "", k, 5);

                        }

                    }
                    PrevAccHistCount=i;
                searchtrue=true;
                current.close();
              
                  }
            catch(SQLException e){ //JOptionPane.showMessageDialog(this,e.getMessage());
            }
                  this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
  jTablehist.requestFocusInWindow();
        }
this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 
        }
    }//GEN-LAST:event_formWindowActivated

    private void jScrollPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane2KeyPressed

    }//GEN-LAST:event_jScrollPane2KeyPressed

    private void jTablehistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablehistKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablehistKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Account acc = new Account();
      acc.jTextFieldClientID.setText(jTextFieldacc.getText().substring(0,7));
      acc.jLabelPix.grabFocus();
      acc.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    String SQL="select -OutstandingBal*interestPercent PrinInt from loans " +
" where LoanID='"+jTableacc.getModel().getValueAt(jTableacc.getSelectedRow(), 2)+"'";
Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
           
  ResultSet current = stmt.executeQuery(SQL);
      if(current.next()){
 jTextFieldBalWithInt.setText(current.getBigDecimal("PrinInt").setScale(2, RoundingMode.HALF_UP)+"");
 
     }else{
          jTextFieldBalWithInt.setText("0");
      }
   current.close();
  //conn.close();
}
catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldBalWithIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBalWithIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBalWithIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelpix;
    private javax.swing.JLabel jLabelsign;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTableacc;
    private javax.swing.JTable jTablehist;
    private javax.swing.JTextField jTextFieldBalC;
    private javax.swing.JTextField jTextFieldBalCU;
    private javax.swing.JTextField jTextFieldBalU;
    private javax.swing.JTextField jTextFieldBalWithInt;
    private javax.swing.JTextField jTextFieldIDcard;
    private javax.swing.JTextField jTextFieldRefno;
    private javax.swing.JTextField jTextFieldacc;
    private javax.swing.JTextField jTextFieldaddress;
    private javax.swing.JTextField jTextFieldbvn;
    private javax.swing.JTextField jTextFieldgroup;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldnuban;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JTextField jTextFieldregdate;
    // End of variables declaration//GEN-END:variables
String searchType="Search on A/C Name";
Clientname search = new Clientname();
int accCount=0;
boolean searchtrue=false;
String ses_date,companyname,compshortname;
String query="select custno,lastname,middlename,firstname,branchcode,homeaddress,phone,ref_no,BVN from clients where lastname+''+middlename+''+firstname like'%";
Global glob = new Global();
Connection conn;
 public String thseparate(BigDecimal amount){
 DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.US);
DecimalFormatSymbols symbols = formatter.getDecimalFormatSymbols();

symbols.setGroupingSeparator(',');
formatter.setDecimalFormatSymbols(symbols);
return formatter.format((amount));    

 }
 
 int  PrevAccHistCount=0;
}
