/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mfbtrans;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Emmanuel
 */

public class PaymentReceipt extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Result
     */
    @Override
      public int print(Graphics g, PageFormat pf, int page) throws PrinterException { 
        if (page>0){
            return NO_SUCH_PAGE;
        }  
         Graphics2D g2d=(Graphics2D)g;
        int x=(int)pf.getImageableX();
        int y=(int)pf.getImageableY();
        g2d.scale(0.7, 0.8);
        g2d.translate(x, y);
     jPanelRcpt.paintAll(g);//does the actual printing
 
        
      
        return PAGE_EXISTS;
    }
    public PaymentReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuRemark = new javax.swing.JPopupMenu();
        Excellent = new javax.swing.JMenuItem();
        VeryGoodResult = new javax.swing.JMenuItem();
        GoodResult = new javax.swing.JMenuItem();
        Satisfactory = new javax.swing.JMenuItem();
        PoorResult = new javax.swing.JMenuItem();
        CouldDoBetter = new javax.swing.JMenuItem();
        KeepItUp = new javax.swing.JMenuItem();
        jLabelmotto1 = new javax.swing.JLabel();
        jPanelRcpt = new javax.swing.JPanel();
        jLabellogo = new javax.swing.JLabel();
        jLabelname = new javax.swing.JLabel();
        jLabelname1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelReceiver3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelpurpose = new javax.swing.JLabel();
        jLabelsum = new javax.swing.JLabel();
        jLabelNon = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelsname10 = new javax.swing.JLabel();
        jLabelsname18 = new javax.swing.JLabel();
        jLabelSumfigure = new javax.swing.JLabel();
        jLabelsname20 = new javax.swing.JLabel();
        jLabelsname21 = new javax.swing.JLabel();
        jLabelsname22 = new javax.swing.JLabel();
        jLabelDate1 = new javax.swing.JLabel();
        jLabeladdress5 = new javax.swing.JLabel();
        jLabelbankpaid = new javax.swing.JLabel();
        jLabelNo = new javax.swing.JTextField();

        jPopupMenuRemark.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuRemarkPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        Excellent.setText("Excellent");
        Excellent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcellentMouseClicked(evt);
            }
        });
        Excellent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcellentActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(Excellent);

        VeryGoodResult.setText("Very Good Result");
        VeryGoodResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeryGoodResultActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(VeryGoodResult);

        GoodResult.setText("Good Result");
        GoodResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodResultActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(GoodResult);

        Satisfactory.setText("Satisfactory");
        Satisfactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatisfactoryActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(Satisfactory);

        PoorResult.setText("Poor Result");
        PoorResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoorResultActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(PoorResult);

        CouldDoBetter.setText("Could Do Better");
        CouldDoBetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouldDoBetterActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(CouldDoBetter);

        KeepItUp.setText("Keep It Up");
        KeepItUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeepItUpActionPerformed(evt);
            }
        });
        jPopupMenuRemark.add(KeepItUp);

        jLabelmotto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelmotto1.setText("RC. 355641");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Receipt");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelRcpt.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRcpt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabelname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelname.setText("HELPING HANDS INITIATIVE");

        jLabelname1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelname1.setText("               CALABAR BRANCH");

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelName.setText("Received From:______________________________________________");

        jLabelReceiver3.setText("_________________________________________________________________________________________________________________");
        jLabelReceiver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelReceiver3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelReceiver3MouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("14 Ekpo Nwa by Mount Zion Road   ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("                    Calabar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("       Cross River State.");

        jLabelpurpose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelpurpose.setText("Being Payment for:_____________________________________________");

        jLabelsum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsum.setText("The Sum Of:__________________________________________________");

        jLabelNon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNon.setText("NO");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDate.setText("Date:______________");

        jLabelsname10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsname10.setText("___________________________________________________________");

        jLabelsname18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsname18.setText("_____________________");

        jLabelSumfigure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSumfigure.setText("N                      :K");
        jLabelSumfigure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelsname20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelsname20.setText("For: Helping Hands Initiative");

        jLabelsname21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsname21.setText("____________");

        jLabelsname22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelsname22.setText("Payer's Signature");

        jLabelDate1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDate1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate1.setText("Official Receipt");
        jLabelDate1.setOpaque(true);

        jLabeladdress5.setBackground(new java.awt.Color(51, 51, 255));
        jLabeladdress5.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabeladdress5.setText("e-Receipt form");
        jLabeladdress5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabeladdress5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladdress5MouseClicked(evt);
            }
        });

        jLabelbankpaid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelbankpaid.setText("Payment made at First City Monument Bank");

        javax.swing.GroupLayout jPanelRcptLayout = new javax.swing.GroupLayout(jPanelRcpt);
        jPanelRcpt.setLayout(jPanelRcptLayout);
        jPanelRcptLayout.setHorizontalGroup(
            jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRcptLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabelDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDate)
                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                        .addComponent(jLabelNon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
            .addGroup(jPanelRcptLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabellogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRcptLayout.createSequentialGroup()
                        .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRcptLayout.createSequentialGroup()
                        .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelname)
                            .addComponent(jLabel2)
                            .addComponent(jLabelname1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
            .addGroup(jPanelRcptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelsum, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelRcptLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRcptLayout.createSequentialGroup()
                        .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelbankpaid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelsname10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(173, 173, 173))
                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                        .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRcptLayout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(jLabeladdress5))
                            .addGroup(jPanelRcptLayout.createSequentialGroup()
                                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                                        .addComponent(jLabelsname18)
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabelSumfigure))
                                    .addComponent(jLabelsname20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelsname22))
                                    .addComponent(jLabelsname21, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelReceiver3, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelRcptLayout.setVerticalGroup(
            jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRcptLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabellogo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                        .addComponent(jLabelname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelname1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)))
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jLabelReceiver3)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNon)
                            .addComponent(jLabelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDate)))
                .addGap(21, 21, 21)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelsum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRcptLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelpurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelsname10)
                .addGap(18, 18, 18)
                .addComponent(jLabelbankpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsname18)
                    .addComponent(jLabelsname21)
                    .addComponent(jLabelSumfigure, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanelRcptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsname20)
                    .addComponent(jLabelsname22))
                .addGap(50, 50, 50)
                .addComponent(jLabeladdress5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRcpt, javax.swing.GroupLayout.PREFERRED_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRcpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Image icon=null;
        try {
            icon = ImageIO.read(getClass().getResource("/exam/school.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
   this.setIconImage(icon); 
   
        String url = "jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=localdatabase";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, "sa", "123456789");
        // String  SQL1 ="select sum(amount),Max(DateEffective) from transactn" +
//"where PaymentID='1'" ; 
           String  SQL ="select * from schoolinfo" ;
       
              Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        ResultSet result = stmt.executeQuery(SQL);
       
        result.next();
        byte[] fileBytes =result.getBytes("logo");
    //OutputStream targetFile= new FileOutputStream("C://Image//new.JPG");  --for writing to file
    //targetFile.write(fileBytes); --for writing to file
    //targetFile.close(); ----for writing to file
     ImageIcon pic=new ImageIcon(fileBytes);
     Image resizpic =pic.getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT);
     ImageIcon resizIcon = new ImageIcon(resizpic);
repaint();
pack();
jLabellogo.setIcon(resizIcon);





      result = stmt.executeQuery(SQL);
      int i=0;
      while(result.next()){
          
     
         
         
         
 i=i+1;
      }
             result.close();
            stmt.close();
            con.close();  
            
        }
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}        // TODO add your handling code here:
                                   
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void ExcellentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcellentMouseClicked

   
 
// TODO add your handling code here:
    }//GEN-LAST:event_ExcellentMouseClicked

    private void KeepItUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeepItUpActionPerformed

     // TODO add your handling code here:
    }//GEN-LAST:event_KeepItUpActionPerformed

    private void jPopupMenuRemarkPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuRemarkPopupMenuWillBecomeInvisible
// TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenuRemarkPopupMenuWillBecomeInvisible

    private void ExcellentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcellentActionPerformed
  
  

            // TODO add your handling code here:
    }//GEN-LAST:event_ExcellentActionPerformed

    private void VeryGoodResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeryGoodResultActionPerformed
  
               // TODO add your handling code here:
    }//GEN-LAST:event_VeryGoodResultActionPerformed

    private void GoodResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodResultActionPerformed
 
      // TODO add your handling code here:
    }//GEN-LAST:event_GoodResultActionPerformed

    private void SatisfactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatisfactoryActionPerformed
     


                // TODO add your handling code here:
    }//GEN-LAST:event_SatisfactoryActionPerformed

    private void PoorResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoorResultActionPerformed

    


                // TODO add your handling code here:
    }//GEN-LAST:event_PoorResultActionPerformed

    private void CouldDoBetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouldDoBetterActionPerformed

  

              // TODO add your handling code here:
    }//GEN-LAST:event_CouldDoBetterActionPerformed

    private void jLabelReceiver3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReceiver3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelReceiver3MousePressed

    private void jLabelReceiver3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReceiver3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelReceiver3MouseReleased

    private void jLabeladdress5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladdress5MouseClicked
 PrinterJob job = PrinterJob.getPrinterJob();
        PageFormat format=job.defaultPage();
        format.setOrientation(PageFormat.PORTRAIT);
        job.setPrintable(this,format);
            boolean ok =job.printDialog();
            
            if(ok){
        try {
            
            job.print();// TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
            } 
         // TODO add your handling code here:
    }//GEN-LAST:event_jLabeladdress5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentReceipt().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CouldDoBetter;
    private javax.swing.JMenuItem Excellent;
    private javax.swing.JMenuItem GoodResult;
    private javax.swing.JMenuItem KeepItUp;
    private javax.swing.JMenuItem PoorResult;
    private javax.swing.JMenuItem Satisfactory;
    private javax.swing.JMenuItem VeryGoodResult;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelDate;
    public javax.swing.JLabel jLabelDate1;
    public javax.swing.JLabel jLabelName;
    public javax.swing.JTextField jLabelNo;
    public javax.swing.JLabel jLabelNon;
    public javax.swing.JLabel jLabelReceiver3;
    public javax.swing.JLabel jLabelSumfigure;
    private javax.swing.JLabel jLabeladdress5;
    public javax.swing.JLabel jLabelbankpaid;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabelmotto1;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelname1;
    public javax.swing.JLabel jLabelpurpose;
    public javax.swing.JLabel jLabelsname10;
    public javax.swing.JLabel jLabelsname18;
    public javax.swing.JLabel jLabelsname20;
    public javax.swing.JLabel jLabelsname21;
    public javax.swing.JLabel jLabelsname22;
    public javax.swing.JLabel jLabelsum;
    private javax.swing.JPanel jPanelRcpt;
    private javax.swing.JPopupMenu jPopupMenuRemark;
    // End of variables declaration//GEN-END:variables
String ses_date,companyname,compshortname;

}
