/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mfbtrans;

import java.awt.Image;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class Payoff extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payoff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPost = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPayID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReference = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBalance = new javax.swing.JTextField();
        jComboBoxBank = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldint = new javax.swing.JTextField();
        jTextFieldprin = new javax.swing.JTextField();
        jButtoncal = new javax.swing.JButton();
        jComboBoxPayType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldChequeno = new javax.swing.JTextField();
        jLabelChequeNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonPost.setMnemonic('P');
        jButtonPost.setText("Post");
        jButtonPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPostActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextFieldDescription.setEditable(false);
        jTextFieldDescription.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel1.setText("Actual Balance");

        jLabel2.setText("Bank");

        jTextFieldAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAmountKeyTyped(evt);
            }
        });

        jLabel3.setText("Description");

        jTextFieldPayID.setEditable(false);

        jLabel4.setText("Payment Reference");

        jTextFieldReference.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NGN" }));

        jLabel6.setText("PaymentID");

        jTextFieldBalance.setEditable(false);

        jComboBoxBank.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBoxBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Zenith Bank", "First Bank", "FCMB", "Diamond", "Standard Chartered Bank", "ECOBank", "Sterling", "Skye", "Fidelity Bank", "Wema", "UBA", "Interconnectal", "Unity" }));

        jLabel7.setText("Payment Amount");

        jLabel8.setText("Principal");

        jLabel9.setText("Interest");

        jTextFieldint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldintMouseExited(evt);
            }
        });

        jTextFieldprin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldprin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldprinMouseExited(evt);
            }
        });

        jButtoncal.setText("Calculate");
        jButtoncal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDescription)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPayID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldReference, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldprin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldint, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoncal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPayID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldint, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtoncal))
                    .addComponent(jTextFieldprin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBank))
                .addContainerGap())
        );

        jComboBoxPayType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Cheque" }));
        jComboBoxPayType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPayTypeActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment Type");

        jTextFieldChequeno.setVisible(false);
        jTextFieldChequeno.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabelChequeNo.setVisible(false);
        jLabelChequeNo.setText("Cheque No:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldChequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jComboBoxPayType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPost, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPayType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPostActionPerformed
jButtoncal.doClick();
      
 PreparedStatement pstmt;
 String Smonth,Sday,ID,amount,pamount,intamount,bal,remark="Paid";
 Calendar now=Calendar.getInstance();
        now.getTime();
        int year=now.get(Calendar.YEAR);
        int Omonth=now.get(Calendar.MONTH);//opening as january=0 not 1
        int day=now.get(Calendar.DAY_OF_MONTH);
         int month=Omonth+1;//note month start with january=0 in java
        Smonth=month+"";
        Sday=day+"";
       if(month<10){Smonth="0"+month;}// let it appear as two digit e.g 02
        if(day<10){Sday="0"+day;}
        Smonth=month+"";
   ID=jTextFieldPayID.getText();
   amount=jTextFieldAmount.getText().toString();
   pamount=jTextFieldprin.getText();
   intamount=jTextFieldint.getText();
   bal=jTextFieldBalance.getText();
   double ovapaid=Double.parseDouble(amount)+Double.parseDouble(bal);
   //check for full or partial payment or over payment
   if(Double.parseDouble(amount)>-(Double.parseDouble(bal)*1.24)){
      JOptionPane.showMessageDialog(this,"Transaction cancelled" +"\n"+"This Account cannot be Overpaid by "+ovapaid);
   } 
   else{
       if(Double.parseDouble(amount)==Double.parseDouble(bal)){
        remark="Serviced";   
       }else{remark="Partially Serviced"; }
       Double RunningAmount=Double.parseDouble(amount);
       while(RunningAmount>=(prinRepay+interest)){ ;
       
       RunningAmount=RunningAmount-(prinRepay+interest);
       complethand=complethand+1;
       }
       if(RunningAmount<=interest){
       IntOnly=true;    
       }
        
 Global glob = new Global();
Connection conn= glob.getConnect();
String query1="update glbal set GlbCredit=GlbCredit+"+Double.parseDouble(pamount)+" where CoaNbr='13101-002' and GlbFinyear='C'"
        + " and glbPeriod='"+Smonth+"'";
String query1b="update glbal set GlbCredit=GlbCredit+"+Double.parseDouble(intamount)+" where CoaNbr='31300' and GlbFinyear='C'"
        + " and glbPeriod='"+Smonth+"'";
String query2="update glbal set Glbdebit=Glbdebit+"+Double.parseDouble(amount)+" where CoaNbr='"+tellerControlGl+"' and GlbFinyear='C'"
  + " and glbPeriod='"+Smonth+"'";

  //convert amount to negative because you are lessing as below:
double amnt=Double.parseDouble(pamount);
String query3="update loans set OutstandingBal=OutstandingBal+"+amnt+" where loanID='"+ID+"'";
String query4=("insert into transactn (AccountID,tranid,Amount,DebitGL,CreditGL,Runningbal,ValueDate,DateEffective,custNo,StmtRef,BranchID,ChequeNbr,CreatedBy)"
        + " values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
String query5="update loanschedule set status='Serviced' where count='"+ repaycount+"'";
  
  //String PayBal=jTablePayment.getModel().getValueAt(jTablePayment.getSelectedRow(),2).toString();
   //JOptionPane.showMessageDialog(this,PayBal);     
    
 
        try{
   
 conn.setAutoCommit(false);//for transaction posting
pstmt=conn.prepareStatement(query1);//update loan  portfolio
pstmt.executeUpdate();

pstmt=conn.prepareStatement(query1b);//update interest income
pstmt.executeUpdate();

pstmt=conn.prepareStatement(query2);
pstmt.executeUpdate();

pstmt=conn.prepareStatement(query3);
pstmt.executeUpdate();

pstmt=conn.prepareStatement(query4);
pstmt.setString(1,ID);
pstmt.setString(2,"001");
pstmt.setString(3,amount);
pstmt.setString(4,tellerControlGl);
pstmt.setString(5,"13101-002");
double curbal=Double.parseDouble(bal)+Double.parseDouble(amount)-Double.parseDouble(intamount);//bal is negative;so plus reduces the bal
pstmt.setString(6,curbal+"");
pstmt.setString(7,ses_date);
pstmt.setString(8,ses_date);
//pstmt.setString(8,year+"-"+Smonth+"-"+Sday);
pstmt.setString(9,jTextFieldPayID.getToolTipText());
pstmt.setString(10,jTextFieldReference.getText());
//JOptionPane.showMessageDialog(this,jTextFieldDescription.getToolTipText());
pstmt.setString(11,AccName);
pstmt.setString(12,jComboBoxBank.getSelectedItem().toString());
pstmt.setString(13,userid);
pstmt.executeUpdate();
pstmt=conn.prepareStatement(query5);
pstmt.executeUpdate();

//updating for interest
pstmt=conn.prepareStatement(query4);
pstmt.setString(1,ID);
pstmt.setString(2,"011");
pstmt.setString(3,intamount);
pstmt.setString(4,tellerControlGl);
pstmt.setString(5,"31300");
pstmt.setString(6,curbal+"");
pstmt.setString(7,ses_date);
pstmt.setString(8,ses_date);
//pstmt.setString(8,year+"-"+Smonth+"-"+Sday);
pstmt.setString(9,jTextFieldPayID.getToolTipText());
pstmt.setString(10,"Interest on Repayment");
//JOptionPane.showMessageDialog(this,jTextFieldDescription.getToolTipText());
pstmt.setString(11,AccName);
pstmt.setString(12,jComboBoxBank.getSelectedItem().toString());
pstmt.setString(13,userid);
pstmt.executeUpdate();
pstmt=conn.prepareStatement(query5);
pstmt.executeUpdate();

//repaycount=repaycount+1;
hands--;
double Tprin=0,Tint=0;
while(complethand>0){
query5="update loanschedule set status='Serviced',servicedprin=servicedprin+'"+prinRepay+"',"
        + "ServicedInt=ServicedInt+'"+interest+"' where count='"+ repaycount +"'"
        + " and loanID='"+ID+"'";
pstmt=conn.prepareStatement(query5);
pstmt.executeUpdate();
Tprin=Tprin+prinRepay;
Tint=Tint+interest;
complethand=complethand-1;
if(repaycount<25){//if will enable the transaction to be posted if wen schedule is exhausted
repaycount=repaycount+1;
}
}
double halfint,halfprin;
if(halfrepay){
   halfprin=Double.parseDouble(jTextFieldprin.getText())-Tprin;
     halfint=Double.parseDouble(jTextFieldint.getText())-Tint;
 query5="update loanschedule set status='Serviced',servicedprin=servicedprin+'"+halfprin+"',"
        + "ServicedInt=ServicedInt+'"+halfint+"' where count='"+ repaycount +"'"
        + " and loanID='"+ID+"'";
pstmt=conn.prepareStatement(query5);
pstmt.executeUpdate();   
}
         conn.commit();//transaction saved
 JOptionPane.showMessageDialog(this,"Done");
 this.setVisible(false);
}
   
catch(Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
try{conn.rollback();}catch(SQLException sqx){//throw new Exception.("Roll back failed: "+sqx.getMessage();)
JOptionPane.showMessageDialog(this, e.getMessage());
}
}this.setVisible(false);
   }//finally {conn.close();}         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPostActionPerformed

    private void jComboBoxPayTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPayTypeActionPerformed
if (jComboBoxPayType.getSelectedItem().toString().equalsIgnoreCase("Cheque")) {
jTextFieldChequeno.setVisible(true); 
jLabelChequeNo.setVisible(true);
jTextFieldReference.setText(jTextFieldReference.getText().toString().replace("cash", "Cheque"));
}
else{
jTextFieldChequeno.setVisible(false); 
jLabelChequeNo.setVisible(false);
jTextFieldReference.setText(jTextFieldReference.getText().toString().replace("Cheque", "Cash"));
}// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPayTypeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Image icon=null;
        try {
            icon = ImageIO.read(getClass().getResource("/exam/school.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
   this.setIconImage(icon); 
           // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldprinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldprinMouseExited
 BigDecimal Amnt= BigDecimal.valueOf(Double.parseDouble(jTextFieldAmount.getText())).setScale(2, RoundingMode.HALF_UP);
 BigDecimal prin= BigDecimal.valueOf(Double.parseDouble(jTextFieldprin.getText())).setScale(2, RoundingMode.HALF_UP);
 
jTextFieldint.setText(Amnt.subtract(prin)+"");      // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprinMouseExited

    private void jTextFieldintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldintMouseExited
 BigDecimal Amnt= BigDecimal.valueOf(Double.parseDouble(jTextFieldAmount.getText())).setScale(2, RoundingMode.HALF_UP);
 BigDecimal intrt= BigDecimal.valueOf(Double.parseDouble(jTextFieldint.getText())).setScale(2, RoundingMode.HALF_UP);
        jTextFieldprin.setText(Amnt.subtract(intrt)+"");              // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldintMouseExited

    private void jTextFieldAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAmountKeyTyped
//jTextFieldint.setText(interest/Amount*Double.parseDouble(jTextFieldAmount.getText())+"");
//jTextFieldprin.setText((Double.parseDouble(jTextFieldAmount.getText())-Double.parseDouble(jTextFieldint.getText()))+"");
// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountKeyTyped

    private void jButtoncalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncalActionPerformed
//JOptionPane.showMessageDialog(this, interest+" "+Amount);
        BigDecimal intrt= BigDecimal.valueOf(interest/Amount*Double.parseDouble(jTextFieldAmount.getText()));
        BigDecimal prin= BigDecimal.valueOf(Double.parseDouble(jTextFieldAmount.getText()));
jTextFieldint.setText(intrt.setScale(2, RoundingMode.HALF_UP)+"");
jTextFieldprin.setText((prin.subtract(intrt.setScale(2, RoundingMode.HALF_UP)))+"");

//get the number of loanschedule to be serviced
BigDecimal hans=null;
BigDecimal amt2 = BigDecimal.valueOf(Double.parseDouble(jTextFieldAmount.getText()));


BigDecimal amt = BigDecimal.valueOf(Amount);

hans=amt2.divide(amt, 2, RoundingMode.UP);

BigDecimal remain=amt2.divide(amt, 0, RoundingMode.UP);
//if(hans.subtract(remain).)){halfrepay=true;}
hands=hans.intValue();
//JOptionPane.showMessageDialog(this, hands+", "+hans+","+halfrepay+" remain="+remain);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payoff().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPost;
    private javax.swing.JButton jButtoncal;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxBank;
    private javax.swing.JComboBox jComboBoxPayType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelChequeNo;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldAmount;
    public javax.swing.JTextField jTextFieldBalance;
    public javax.swing.JTextField jTextFieldChequeno;
    public javax.swing.JTextField jTextFieldDescription;
    public javax.swing.JTextField jTextFieldPayID;
    public javax.swing.JTextField jTextFieldReference;
    public javax.swing.JTextField jTextFieldint;
    public javax.swing.JTextField jTextFieldprin;
    // End of variables declaration//GEN-END:variables

public double prinRepay,interest,Amount;
boolean halfrepay=false,IntOnly=false;;
int repaycount,hands,complethand=0;
String AccName="";
String tellerControlGl;
String userid;
String ses_date,companyname,compshortname;
}
