/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mfbtrans;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCommit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldStaffId = new javax.swing.JTextField();
        jTextFieldFn = new javax.swing.JTextField();
        jTextFieldMn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxUrole = new javax.swing.JComboBox();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPasswordFieldPw = new javax.swing.JPasswordField();
        jPasswordFieldCfm = new javax.swing.JPasswordField();
        jButtonReset = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jTextFieldUname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Profile");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));

        jButtonCommit.setText("Commit");
        jButtonCommit.setEnabled(false);
        jButtonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("UserName");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("StaffID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("MiddleName");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("UserRole");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Status");

        jComboBoxUrole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marketer", "Manager", "MIS Supervisor", "Teller1", "Teller2", "Teller3", "Teller4", "Teller5", "DES-MIS", "ACCOUNTANT", "CSO", "Administrator" }));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Active", "Inactive", "Closed" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Confirm");

        jButtonReset.setText("Reset ");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNew.setText("new");
        jButtonNew.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jTextFieldUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnameActionPerformed(evt);
            }
        });

        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyPressed(evt);
            }
        });

        jLabelID.setText("UserID");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete User");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButtonSearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSearch)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jButtonEdit.setText("Save Changes");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxUrole, 0, 182, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStaffId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldFn)
                                    .addComponent(jTextFieldMn)
                                    .addComponent(jTextFieldLn)
                                    .addComponent(jPasswordFieldPw)
                                    .addComponent(jPasswordFieldCfm)
                                    .addComponent(jTextFieldUname, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEdit)
                            .addComponent(jButtonCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jPasswordFieldPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jPasswordFieldCfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReset)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEdit)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommitActionPerformed
//check for incomplete form
        if(jTextFieldUname.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No UserID Entered");}
        else if(jTextFieldStaffId.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No StaffID Entered");}
else if (jTextFieldFn.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No first name Entered");}
else if (jTextFieldLn.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No Last Name Entered");}
else if (jPasswordFieldPw.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No Password Entered");}
else if (jComboBoxUrole.getSelectedItem().toString().isEmpty()){JOptionPane.showMessageDialog(this,"No User Role Selected");}
else if(jComboBoxStatus.getSelectedItem().toString().isEmpty()){JOptionPane.showMessageDialog(this,"No Status Selected");}
else if(jPasswordFieldCfm.getText().isEmpty()){JOptionPane.showMessageDialog(this,"You must fill Comfirm Password");}
else{
if(!jPasswordFieldPw.getText().equalsIgnoreCase(jPasswordFieldCfm.getText())){
    JOptionPane.showMessageDialog(this,"Password and Comfirm Password does not Match");
    
}
else{
//IP=jButtonCommit.getToolTipText();
if (IP==null){IP="localhost";}

 
  String query;
PreparedStatement pstmt; 
Statement stmt ;
Connection conn=glob.getConnect();

try
{
    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
     
query=("insert into usertable VALUES (?,?,?,?,?,?,?,?,?)");
pstmt=conn.prepareStatement(query);
pstmt.setString(1,jTextFieldUname.getText());
pstmt.setString(2,jTextFieldStaffId.getText());
pstmt.setString(3,jTextFieldFn.getText());
pstmt.setString(4,jTextFieldMn.getText());
pstmt.setString(5,jTextFieldLn.getText());
pstmt.setString(6,jPasswordFieldPw.getText());
pstmt.setString(7,jComboBoxUrole.getSelectedItem().toString());
pstmt.setString(8,jComboBoxStatus.getSelectedItem().toString());


Calendar now=Calendar.getInstance();
        now.getTime();
        int year=now.get(Calendar.YEAR);
        String Smonth,Sday;
        int Omonth=now.get(Calendar.MONTH);//opening as january=0 not 1
        int day=now.get(Calendar.DAY_OF_MONTH);
         int month=Omonth+1;//note month start with january=0 in java
        Smonth=month+"";
        Sday=day+"";
       if(month<10){Smonth="0"+month;}// let it appear as two digit e.g 02
        if(day<10){Sday="0"+day;}
pstmt.setString(9,year+"-"+Smonth+"-"+Sday+" 00:00:00.000");
pstmt.executeUpdate();
if(jComboBoxUrole.getSelectedItem().toString().contains("eller")){
    String CheckGl="select * from Glcoa where coaname ='"+jComboBoxUrole.getSelectedItem().toString()+"'";
    stmt=conn.createStatement();
    ResultSet rs= stmt.executeQuery(CheckGl);
    if(rs.next()){
      //do nothing  
    }
    else{
        //create the teller in the Glcoa Table
        String Glcode=jComboBoxUrole.getSelectedItem().toString().substring(6); 
        int tellerNo=Integer.parseInt(Glcode)+2;
        Glcode="1110"+tellerNo+"-"+BranCODE;
        JOptionPane.showMessageDialog(this,jComboBoxUrole.getSelectedItem().toString()+" GLCODE IS "+Glcode );
        String CrTellerInGL="insert into GLCoa(CoaNbr,Status,CoaName,CoaType,CoaSign,CoaControl,CoaHeader,CoaRepLevel) values('"+Glcode+"','A','"+jComboBoxUrole.getSelectedItem().toString()+"','A','D','0','0','3')";
        pstmt=conn.prepareStatement(CrTellerInGL);
        pstmt.executeUpdate();
    }
}
JOptionPane.showMessageDialog(this,"User Created successfully");
jTextFieldUname.setText("");
jTextFieldStaffId.setText("");
jTextFieldFn.setText("");
jTextFieldMn.setText("");
jTextFieldLn.setText("");
jPasswordFieldPw.setText("");
jPasswordFieldCfm.setText("");
jComboBoxUrole.setSelectedItem("");
jComboBoxStatus.setSelectedItem("");

     }
catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());

}
}    
}// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCommitActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
if(jButtonOK.isVisible()){
    jButtonOK.setVisible(false);
    jTextFieldID.setVisible(false);
    jLabelID.setVisible(false);
    jButtonCommit.setEnabled(true);
    jTextFieldID.setText("");
    jTextFieldUname.setText("");
    jTextFieldStaffId.setText(""); 
             jTextFieldFn.setText("");
             jTextFieldMn.setText("");
             jTextFieldLn.setText("");
             jPasswordFieldPw.setText("");
             jPasswordFieldCfm.setText("");
             jComboBoxUrole.setSelectedIndex(0);
             jComboBoxStatus.setSelectedIndex(0);
             jButtonReset.setEnabled(false);
}
else{jButtonOK.setVisible(true);
    jTextFieldID.setVisible(true);
    jLabelID.setVisible(true);
    jButtonCommit.setEnabled(false);
    jTextFieldID.requestFocusInWindow();
    jButtonReset.setEnabled(true);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
 jButtonCommit.setEnabled(false);//Disable commit button
//IP=jButtonCommit.getToolTipText();
if (IP==null){IP="localhost";}//in case no ip has been set use localhost to connect

        String test = "Connection Succeeded";

            boolean login=false;
        //Global glob= new Global();
       // String url = "jdbc:sqlserver://"+IP+"\\SQLEXPRESS:1433;databaseName=BankDatabase";

         String NoUsermsg = "No Matric number entered";
        String NoPasswdmsg = "No Exam number Entered";
        String UsrIncorMsg = "Incorrect User Name";
        String PasswdIncorMsg = "Incorrect Password or UserID";





        if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, NoUsermsg, "Enter Your UserID", WIDTH);
        } 
        
        
        else{



        try {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           // Connection con = DriverManager.getConnection(url, "sa", "123456789");
            Connection con =glob.getConnect();
            Statement select = con.createStatement();
            ResultSet result = select.executeQuery("SELECT * FROM Usertable");
            String  user=jTextFieldID.getText();
            
            
            String usID;
          while (result.next()){
           usID=result.getString("Userid");
          if (user.equalsIgnoreCase(usID)){
              
             jTextFieldUname.setText(result.getString("Userid"));
             jTextFieldStaffId.setText(result.getString("StaffID")); 
             jTextFieldFn.setText(result.getString("FirstNm"));
             jTextFieldMn.setText(result.getString("MidNm"));
             jTextFieldLn.setText(result.getString("LstNm"));
             jPasswordFieldPw.setText(result.getString("Password"));
             jComboBoxUrole.setSelectedItem(result.getString("UserRole"));
             jComboBoxStatus.setSelectedItem(result.getString("Usr_Status"));
    
          
             
  login=true;
        jButtonNew.setEnabled(true);
       jButtonDelete.setEnabled(true);
  jButtonEdit.setEnabled(true);//Enable Edit button
           }
          
       
        }
          if (login==false){JOptionPane.showMessageDialog(this, "Sorry,User not Found!!!");}
           result.close();
            select.close();
            con.close();
         
        }
catch (  SQLException | HeadlessException e) {
  
        JOptionPane.showMessageDialog(this,e.getMessage(), "Authentication Failed",WIDTH);   
          
        
        
}          
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
jButtonOK.setVisible(false);
    jTextFieldID.setVisible(false);
    jLabelID.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code hereIP=jButtonCommit.getToolTipText();
if(!jPasswordFieldPw.getText().equalsIgnoreCase(jPasswordFieldCfm.getText())){
    JOptionPane.showMessageDialog(this,"Password and Comfirm Password does not Match");
    
}else{
//if (IP==null){IP="localhost";}
// String url =  "jdbc:sqlserver://"+IP+"\\SQLEXPRESS:1433;databaseName=BankDatabase";
  String query;
PreparedStatement pstmt;      
Connection conn=null;

try
{
    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
     conn = glob.getConnect();
query=("update usertable set PassWord='"+jPasswordFieldPw.getText()+"'"+
"where userID='"+jTextFieldID.getText())+"'";
pstmt=conn.prepareStatement(query);

pstmt.executeUpdate();
JOptionPane.showMessageDialog(this,"User Password reset successful");


     }
catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());

}
}  
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
String msg="Are you sure you want to delete user?"+"\n" + "Click NO to cancall user delete";
final JDialog w= new JDialog();
w.setSize(300,200);
w.setLocation(500,200);
w.setTitle("Delete the User");
w.isAlwaysOnTop();
final JOptionPane optionPane= new JOptionPane(msg);
optionPane.setMessageType(JOptionPane.QUESTION_MESSAGE);
optionPane.setOptionType(0);
optionPane.isShowing();
w.setContentPane(optionPane);
w.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
w.setModal(true);
w.getMostRecentFocusOwner();
optionPane.addPropertyChangeListener(
    new PropertyChangeListener() {
        public void propertyChange(PropertyChangeEvent e) {
            String prop = e.getPropertyName();

            if (w.isVisible() 
             && (e.getSource() == optionPane)
             && (prop.equals(JOptionPane.VALUE_PROPERTY))) {
            w.setVisible(false);
            }
        }
    
            });

w.show();      
w.pack();
int value = ((Integer)optionPane.getValue()).intValue();
if (value == JOptionPane.YES_OPTION) {  //Delete operation continues as user selected yes 
        
        String query,Userid=jTextFieldID.getText();
        PreparedStatement pstmt;
      
        Connection conn=null;

        try
        {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = glob.getConnect();
            query=("delete from usertable where userid='"+Userid+"'");
            pstmt=conn.prepareStatement(query);
            pstmt.executeUpdate();
           
            JOptionPane.showMessageDialog(this, "User deleted Successfully");
            jTextFieldUname.setText("");//to clear the text box
            jTextFieldStaffId.setText("");
            jTextFieldLn.setText("");
            jTextFieldFn.setText("");
            jTextFieldMn.setText("");
            jPasswordFieldPw.setText("");
            jPasswordFieldCfm.setText("");
            jComboBoxUrole.setSelectedItem("");
            jComboBoxStatus.setSelectedItem("");
           
            jTextFieldID.setText("");

jButtonDelete.setEnabled(false);//prevent user from clicking delete twice
jButtonNew.setEnabled(true);
        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        } else if (value == JOptionPane.NO_OPTION) {
     JOptionPane.showMessageDialog(this,"Delete operation was cancalled by user");
}// TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
if(jTextFieldUname.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No UserID Entered");}
        else if(jTextFieldStaffId.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No StaffID Entered");}
else if (jTextFieldFn.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No first name Entered");}
else if (jTextFieldLn.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No Last Name Entered");}
else if (jPasswordFieldPw.getText().isEmpty()){JOptionPane.showMessageDialog(this,"No Password Entered");}
else if (jComboBoxUrole.getSelectedItem().toString().isEmpty()){JOptionPane.showMessageDialog(this,"No User Role Selected");}
else if(jComboBoxStatus.getSelectedItem().toString().isEmpty()){JOptionPane.showMessageDialog(this,"No Status Selected");}
else if(jPasswordFieldCfm.getText().isEmpty()){JOptionPane.showMessageDialog(this,"You must fill Comfirm Password");}
else{String query,Userid=jTextFieldID.getText();
        PreparedStatement pstmt;
        Statement stmt;
        

     String un=jTextFieldID.getText(),sid=jTextFieldStaffId.getText(),
   ln=jTextFieldLn.getText(),
          fn=  jTextFieldFn.getText(),
            mn=jTextFieldMn.getText(),
            pw=jPasswordFieldPw.getText(),
            ur=jComboBoxUrole.getSelectedItem().toString(),
            st=jComboBoxStatus.getSelectedItem().toString(),
           
            id=jTextFieldID.getText(); 
     
Calendar now=Calendar.getInstance();
        now.getTime();
        int year=now.get(Calendar.YEAR);
        String Smonth,Sday;
        int Omonth=now.get(Calendar.MONTH);//opening as january=0 not 1
        int day=now.get(Calendar.DAY_OF_MONTH);
         int month=Omonth+1;//note month start with january=0 in java
        Smonth=month+"";
        Sday=day+"";
       if(month<10){Smonth="0"+month;}// let it appear as two digit e.g 02
        if(day<10){Sday="0"+day;}

String date=year+"-"+Smonth+"-"+Sday+" 00:00:00.000";


        Connection conn=null;

        try
        {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = glob.getConnect();
            query=("update Usertable set staffid='"+sid+"',FirstNm='"+fn+"',Midnm='"+mn+"',LstNm='"+ln+"',Password='"+pw+"',"
                    + "UserRole='"+ur+"',usr_Status='"+st+"',Date_Created='"+date+"' where userid='"+id+"'");
pstmt=conn.prepareStatement(query);

            pstmt.executeUpdate();
           if(jComboBoxUrole.getSelectedItem().toString().contains("eller")){
    String CheckGl="select * from Glcoa where coaname ='"+jComboBoxUrole.getSelectedItem().toString()+"'";
    stmt=conn.createStatement();
    ResultSet rs= stmt.executeQuery(CheckGl);
    if(rs.next()){
      //do nothing  
    }
    else{
        //create the teller in the Glcoa Table
        String Glcode=jComboBoxUrole.getSelectedItem().toString().substring(6); 
        int tellerNo=Integer.parseInt(Glcode)+2;
        Glcode="1110"+tellerNo+"-"+BranCODE;
        JOptionPane.showMessageDialog(this,jComboBoxUrole.getSelectedItem().toString()+" GLCODE IS "+Glcode );
        String CrTellerInGL="insert into GLCoa(CoaNbr,Status,CoaName,CoaType,CoaSign,CoaControl,CoaHeader,CoaRepLevel) values('"+Glcode+"','A','"+jComboBoxUrole.getSelectedItem().toString()+"','A','D','0','0','3')";
        pstmt=conn.prepareStatement(CrTellerInGL);
        pstmt.executeUpdate();
    }
}
            JOptionPane.showMessageDialog(this, "User Edited Successfully");
            

jButtonEdit.setEnabled(false);
jButtonNew.setEnabled(true);//prevent user from clicking edit twice
        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
}
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
jTextFieldUname.setText("");//to clear the text box
            jTextFieldStaffId.setText("");
            jTextFieldLn.setText("");
            jTextFieldFn.setText("");
            jTextFieldMn.setText("");
            jPasswordFieldPw.setText("");
            jPasswordFieldCfm.setText("");
            jComboBoxUrole.setSelectedItem("");
            jComboBoxStatus.setSelectedItem("");
            jTextFieldID.setText("");
            jButtonSearch.doClick();
jButtonCommit.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jTextFieldUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUnameActionPerformed

    private void jTextFieldIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyPressed
 
 if (evt.getKeyCode()==KeyEvent.VK_ENTER ||evt.getKeyCode()==KeyEvent.VK_HOME){jButtonOK.doClick();}          // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection con =glob.getConnect();
            Statement select = con.createStatement();
            ResultSet result = select.executeQuery("SELECT Branchcode FROM BranchCode");
            if(result.next()){
             BranCODE= result.getString("Branchcode");
            }
            else{
               JOptionPane.showMessageDialog(rootPane, "No branch code exist,\n the branch is not configured ");  
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCommit;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JComboBox jComboBoxUrole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldCfm;
    private javax.swing.JPasswordField jPasswordFieldPw;
    private javax.swing.JTextField jTextFieldFn;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLn;
    private javax.swing.JTextField jTextFieldMn;
    private javax.swing.JTextField jTextFieldStaffId;
    private javax.swing.JTextField jTextFieldUname;
    // End of variables declaration//GEN-END:variables
String IP, BranCODE;
String userid;
String ses_date,companyname,compshortname;
Global glob = new Global();
}
