/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mfbtrans;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class Withdrawal extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Withdrawal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPost = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPayID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReference = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBalance = new javax.swing.JTextField();
        jComboBoxBank = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabelR = new javax.swing.JLabel();
        jComboBoxPayType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldChequeno = new javax.swing.JTextField();
        jLabelChequeNo = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Withdrawer Details");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonPost.setMnemonic('P');
        jButtonPost.setText("Post");
        jButtonPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPostActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextFieldDescription.setEditable(false);
        jTextFieldDescription.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel1.setText("Actual Balance");

        jLabel2.setText("Bank");

        jTextFieldAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAmountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAmountKeyTyped(evt);
            }
        });

        jLabel3.setText("Description");

        jTextFieldPayID.setEditable(false);

        jLabel4.setText("Payment Reference");

        jTextFieldReference.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NGN" }));

        jLabel6.setText("AccountID");

        jTextFieldBalance.setEditable(false);

        jComboBoxBank.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBoxBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zenith Bank", "First Bank", "FCMB", "Diamond", "Standard Chartered Bank", "ECOBank", "Sterling", "Skye", "Fidelity Bank", "Wema", "UBA", "Interconnectal", "Unity" }));

        jLabel7.setText("Deposit Amount");

        jLabelR.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDescription)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPayID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldReference, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPayID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(jLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBank))
                .addContainerGap())
        );

        jComboBoxPayType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Cheque" }));
        jComboBoxPayType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPayTypeActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment Type");

        jTextFieldChequeno.setVisible(false);
        jTextFieldChequeno.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabelChequeNo.setVisible(false);
        jLabelChequeNo.setText("Cheque No:");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldChequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPayType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPost, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxPayType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonPost)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPostActionPerformed
String dd=jDateChooser1.getDate().toString();
        String m="";
        if(dd.contains("Jan")){m="01";}
        else if(dd.contains("Feb")){m="02";}
         else if(dd.contains("Mar")){m="03";}
         else if(dd.contains("Apr")){m="04";}
         else if(dd.contains("May")){m="05";}
         else if(dd.contains("Jun")){m="06";}
        else if(dd.contains("Jul")){m="07";}
        else if(dd.contains("Aug")){m="08";}
        else if(dd.contains("Sep")){m="09";}
        else if(dd.contains("Oct")){m="10";}
        else if(dd.contains("Nov")){m="11";}
        else if(dd.contains("Dec")){m="12";}
String SelectedDate= dd.substring(dd.length()-4)+"-"+m+"-"+dd.substring(8,10);

        
String StrQuery="select GLCode,intGL from Product where productid like'"+jTextFieldDescription.getText().substring(0,3)+"%Sav%'";

     
       // SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS aa");
 //Date cdate = new Date();
  //String strnow=sdf.format(cdate);
  String strnow=SelectedDate; 
      
 PreparedStatement pstmt;
 String Smonth,Sday,ID,amount,bal,remark="Paid",tranid="005";
 Calendar now=Calendar.getInstance();
        now.getTime();
        int year=now.get(Calendar.YEAR);
        int Omonth=now.get(Calendar.MONTH);//opening as january=0 not 1
        int day=now.get(Calendar.DAY_OF_MONTH);
         int month=Omonth+1;//note month start with january=0 in java
        Smonth=month+"";
        Sday=day+"";
       if(month<10){Smonth="0"+month;}// let it appear as two digit e.g 02
        if(day<10){Sday="0"+day;}
        Smonth=month+"";
   ID=jTextFieldPayID.getText();
   amount=jTextFieldAmount.getText();
   bal=jTextFieldBalance.getText();
  Double ovapaid=Double.parseDouble(bal)-Double.parseDouble(amount);
   //check for full or partial payment or over payment
    if(!jTextFieldPayID.getText().startsWith("2")){JOptionPane.showMessageDialog(rootPane, "Invalid Transaction");this.dispose();}
 
    else  if(Double.parseDouble(amount)>Double.parseDouble(bal) ){
      JOptionPane.showMessageDialog(this,"Transaction cancelled" +"\n"+"This Account cannot be Over-Withdrawn by "+ovapaid);
   } 
   else{
    String SavingGL="24101",IntExpGL;
 Global glob = new Global();
Connection conn= glob.getConnect();
   try{
 Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);

ResultSet cur = stmt.executeQuery(StrQuery);
        cur.next();
 SavingGL=cur.getString("GLCode")+"-"+BranchCode;
 //JOptionPane.showMessageDialog(this, SavingGL);
 IntExpGL=cur.getString("intGL")+"-"+BranchCode;
   }
   catch(SQLException e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
String query1="update glbal set Glbdebit=Glbdebit+"+Double.parseDouble(amount)+" where CoaNbr='"+ SavingGL+"' and GlbFinyear='C'"
        + " and glbPeriod='"+ses_date.substring(5,7)+"'";
String query2="update glbal set GlbCredit=GlbCredit+"+Double.parseDouble(amount)+" where CoaNbr='"+tellerControlGl+"' and GlbFinyear='C'"
  + " and glbPeriod='"+ses_date.substring(5,7)+"'";
  //convert amount to negative because you are lessing as below:
Double amnt=Double.parseDouble(amount);
if(withdrFlag==true){amnt=-amnt;tranid="005";}
String query3="update Deposit  set RunningBal=RunningBal-"+amnt+" where AccountID='"+ID+"'";
String query4=("insert into transactn (AccountID,tranid,Amount,CreditGL,DebitGL,Runningbal,ValueDate,DateEffective,CustNO,StmtRef,BranchID,ChequeNbr,CreatedBy,transactionNbr)"
        + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

  //String PayBal=jTablePayment.getModel().getValueAt(jTablePayment.getSelectedRow(),2).toString();
       
     
        try{
            //generating transaction number
    Timestamp timestamp = new Timestamp(System.currentTimeMillis());    
        Random rand = new Random(timestamp.getTime());
        int Rnum=rand.nextInt(999999);
String tranctno=strnow.substring(2, 4)+strnow.substring(5, 7)+strnow.substring(8,10)+Rnum+"CWR";
  

 conn.setAutoCommit(false);//for transaction posting
 
pstmt=conn.prepareStatement(query1);
pstmt.executeUpdate();

pstmt=conn.prepareStatement(query2);
pstmt.executeUpdate();
pstmt=conn.prepareStatement(query3);
pstmt.executeUpdate();
 
pstmt=conn.prepareStatement(query4);
pstmt.setString(1,ID);
pstmt.setString(2,tranid);
pstmt.setString(3,amnt+"");
pstmt.setString(4,tellerControlGl);
pstmt.setString(5, SavingGL);
Double curbal=Double.parseDouble(bal)-amnt;
pstmt.setString(6,curbal+"");
pstmt.setString(7,ses_date);
pstmt.setString(8,ses_date);
//pstmt.setString(8,strnow);
pstmt.setString(9,jTextFieldPayID.getToolTipText());
pstmt.setString(10,jTextFieldReference.getText());
//JOptionPane.showMessageDialog(this,jTextFieldDescription.getToolTipText());
pstmt.setString(11,jTextFieldDescription.getToolTipText());
pstmt.setString(12,jComboBoxBank.getSelectedItem().toString());
pstmt.setString(13,userid);
pstmt.setString(14,tranctno);
pstmt.executeUpdate();





         conn.commit();//transaction saved
 JOptionPane.showMessageDialog(this,"Done");
 this.setVisible(false);
}
   
catch(Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
try{conn.rollback();}catch(SQLException sqx){//throw new Exception.("Roll back failed: "+sqx.getMessage();)
JOptionPane.showMessageDialog(this, e.getMessage());
}
}this.setVisible(false);
   }//finally {conn.close();}         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPostActionPerformed

    private void jComboBoxPayTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPayTypeActionPerformed
if (jComboBoxPayType.getSelectedItem().toString().equalsIgnoreCase("Cheque")) {
jTextFieldChequeno.setVisible(true); 
jLabelChequeNo.setVisible(true);
jTextFieldReference.setText(jTextFieldReference.getText().toString().replace("cash", "Cheque"));
}
else{
jTextFieldChequeno.setVisible(false); 
jLabelChequeNo.setVisible(false);
jTextFieldReference.setText(jTextFieldReference.getText().toString().replace("Cheque", "Cash"));
}// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPayTypeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{//JOptionPane.showMessageDialog(rootPane, ses_date);
         Date cdate = new SimpleDateFormat("yyyy-MM-dd").parse( ses_date);
        //Date cdate =new Date((Date).parse(ses_date)); 

           jDateChooser1.setDate(cdate); 
}
catch(ParseException e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
        Image icon=null;
        try {
            icon = ImageIO.read(getClass().getResource("/exam/school.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
   this.setIconImage(icon); 
           
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAmountKeyTyped

          if(jTextFieldAmount.getText().startsWith("-")){
    jLabelR.setText("Format error");
       jLabelR.setVisible(true);
       jButtonPost.setEnabled(false);
}else{
     jLabelR.setVisible(false);
     jButtonPost.setEnabled(true);
}
    }//GEN-LAST:event_jTextFieldAmountKeyTyped

    private void jTextFieldAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAmountKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){jButtonPost.doClick();}
    }//GEN-LAST:event_jTextFieldAmountKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdrawal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPost;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxBank;
    private javax.swing.JComboBox jComboBoxPayType;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelChequeNo;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldAmount;
    public javax.swing.JTextField jTextFieldBalance;
    public javax.swing.JTextField jTextFieldChequeno;
    public javax.swing.JTextField jTextFieldDescription;
    public javax.swing.JTextField jTextFieldPayID;
    public javax.swing.JTextField jTextFieldReference;
    // End of variables declaration//GEN-END:variables

boolean withdrFlag=false;
String userid;
String tellerControlGl,BranchCode;
String ses_date,companyname,compshortname;
}
